version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydatabase
      DB_AUTO_LOAD_ENTITIES: 'true'
      DB_SYNCHRONIZE: 'true'
      OPENAI_API_KEY: ''
      OPENAI_ASSISTANT_ID: ''
      CORS_ORIGIN: 'http://localhost:5173'
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: